### ISSUE TITLE
Why is it so slow to start?

### ISSUE THREAD

**Issue by 677230756E64** [owasp-amass/amass#1027]
Even if I just want to list sources like so `amass enum -list` it takes like 5 minutes to just show them, all the while putting a constant load on my cpu. What's it doing under the hood during that?

**Comment by mbezhanov** [comment]
> What's it doing under the hood during that?

It's sending out a large number of DNS queries to verify that every server in the group of untrusted DNS resolvers responds to queries without exposing your client information.

By default, unless you provide a specific list of untrusted resolvers, Amass will automatically use its default pool of around 58 000 untrusted DNS resolvers to perform these checks.

As you just want to list the available sources without performing any actual scans, you can specify the list of untrusted resolvers explicitly in order to speed things up, e.g.:

```
amass enum -list -r 8.8.4.4
```

On my end, this reduces startup time to about 10-12 seconds (most of which are spent populating the ASN cache, but that's another story).

**Comment by caffix** [comment]
Please use the Amass Docker Compose. All the tools are available in the compose environment
